experiment_name: case118_warm_starting
log_dir: logs

model:
  type: warm_starting
  hidden_dims: [128, 256, 128]
  dropout_rate: 0.1

training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 20
  early_stopping: 5
  optimizer: adam
  criterion: mse
  validation_split: 0.1
  use_wandb: false
  seed: 42

data:
  case: case118
  data_dir: data
  test_size: 0.1
  cv_folds: 5
  use_augmentation: false
  normalize_inputs: true
  normalize_outputs: true 